name: ChromeOS- Lift Device Containment
provision_on_install: true
trigger:
    next:
        - chromeos___convert_host_id_6903f0f1
    name: On demand
    parameters:
        properties:
            host_id:
                type: string
        type: object
actions:
    chromeos___convert_host_id_6903f0f1:
        id: functions.ConvertDeviceId.ChromeOS - Convert Host ID
        properties:
            host_id: ${host_id}
