name: ChromeOS Device Containment
parameters:
    actions:
        configuration:
            chromeos__get_device_info_ad9f45a5:
                properties:
                    params.path.customerId:
                        required: true
            chromeos__move_devices_to_ou_f0df763d:
                properties:
                    params.path.customerId:
                        required: true
                    params.query.OrgUnitPath:
                        required: true
provision_on_install: true
trigger:
    next:
        - sensor_platform_is_equal_to_chromeos_063ef9ab
    event: Investigatable/EPP
actions:
    add_ou_to_collection_1627d968:
        next:
            - chromeos__move_devices_to_ou_f0df763d
        id: functions.CollectionActions.add_ou_to_collection
        properties:
            existing_ou_id: ${chromeos__get_device_info_ad9f45a5.API_Integration.Custom_ChromeOS_API.ChromeOS-_Get_Device_Info.body.orgUnitId}
            host_id: ${Trigger.Category.Investigatable.Product.EPP.Sensor.SensorID}
    chromeos___convert_host_id_58ab92a8:
        next:
            - chromeos__get_device_info_ad9f45a5
        id: functions.ConvertDeviceId.ChromeOS - Convert Host ID
        properties:
            host_id: ${Trigger.Category.Investigatable.Product.EPP.Sensor.SensorID}
    chromeos__get_device_info_ad9f45a5:
        next:
            - add_ou_to_collection_1627d968
        id: api_integrations.ChromeOS API.ChromeOS- Get Device Info
        properties:
            params:
                path:
                    deviceId: ${chromeos___convert_host_id_58ab92a8.FaaS.ConvertDeviceId.ChromeOS-ConvertHostID.device_id}
    chromeos__move_devices_to_ou_f0df763d:
        id: api_integrations.ChromeOS API.ChromeOS- Move Devices to OU
        properties:
            json:
                deviceIds:
                    - ${chromeos__get_device_info_ad9f45a5.API_Integration.Custom_ChromeOS_API.ChromeOS-_Get_Device_Info.body.deviceId}
conditions:
    sensor_platform_is_equal_to_chromeos_063ef9ab:
        next:
            - chromeos___convert_host_id_58ab92a8
        expression: Trigger.Category.Investigatable.Product.EPP.Sensor.Platform:'ChromeOS'
        display:
            - Sensor platform is equal to ChromeOS
