name: Lift Device Containment 2
provision_on_install: true
trigger:
    next:
        - chromeos___convert_host_id_23f00ded
    name: On demand
    parameters:
        properties:
            host_id:
                type: string
        type: object
actions:
    chromeos___convert_host_id_23f00ded:
        next:
            - get_ou_from_collection_743e2907
        id: functions.convert-device-id.ChromeOS - Convert Host ID
        properties:
            host_id: ${host_id}
    chromeos__change_device_status_58f476bb:
        id: api_integrations.chromeos-api.ChromeOS- Change Device Status
        properties:
            json:
                changeChromeOsDeviceStatusAction: CHANGE_CHROME_OS_DEVICE_STATUS_ACTION_REENABLE
                deviceIds:
                    - ${chromeos__get_device_info_65995209.API_Integration.Custom_chromeos-api.ChromeOS-_Get_Device_Info.body.deviceId}
            params:
                path:
                    customer_id: ${get_settings_from_collection_8db0d6a3.FaaS.collection-actions.get_settings_from_collection.customer_id}
    chromeos__get_device_info_65995209:
        next:
            - chromeos__move_device_to_ou_4b52c94e
        id: api_integrations.chromeos-api.ChromeOS- Get Device Info
        properties:
            params:
                path:
                    customerId: ${get_settings_from_collection_8db0d6a3.FaaS.collection-actions.get_settings_from_collection.customer_id}
                    deviceId: ${chromeos___convert_host_id_23f00ded.FaaS.convert-device-id.ChromeOS-ConvertHostID.device_id}
    chromeos__move_device_to_ou_4b52c94e:
        next:
            - status_is_equal_to_inactive_5c14f157
        id: api_integrations.chromeos-api.ChromeOS- Move Device to OU
        properties:
            json:
                deviceIds:
                    - ${chromeos___convert_host_id_23f00ded.FaaS.convert-device-id.ChromeOS-ConvertHostID.device_id}
            params:
                path:
                    customerId: ${get_settings_from_collection_8db0d6a3.FaaS.collection-actions.get_settings_from_collection.customer_id}
                query:
                    orgUnitPath: ${get_settings_from_collection_8db0d6a3.FaaS.collection-actions.get_settings_from_collection.containment_ou}
    get_ou_from_collection_743e2907:
        next:
            - get_settings_from_collection_8db0d6a3
        id: functions.collection-actions.get_ou_from_collection
        properties:
            host_id: ${host_id}
    get_settings_from_collection_8db0d6a3:
        next:
            - chromeos__get_device_info_65995209
        id: functions.collection-actions.get_settings_from_collection
        properties: {}
conditions:
    status_is_equal_to_inactive_5c14f157:
        next:
            - chromeos__change_device_status_58f476bb
        expression: chromeos__get_device_info_65995209.API_Integration.Custom_chromeos-api.ChromeOS-_Get_Device_Info.body.status:'INACTIVE'
        display:
            - Status is equal to INACTIVE
