name: ChromeOS Lift Containment
parameters:
    actions:
        configuration:
            chromeos__move_devices_to_ou_d049cc27:
                properties:
                    params.path.customerId:
                        required: true
provision_on_install: true
trigger:
    next:
        - chromeos___convert_host_id_6b37a758
    name: On demand
    parameters:
        properties:
            host_id:
                type: string
        type: object
actions:
    chromeos___convert_host_id_6b37a758:
        next:
            - get_ou_from_collection_8377f9b2
        id: functions.ConvertDeviceId.ChromeOS - Convert Host ID
        properties:
            host_id: ${host_id}
    chromeos__move_devices_to_ou_d049cc27:
        id: api_integrations.ChromeOS API.ChromeOS- Move Devices to OU
        properties:
            json:
                deviceIds:
                    - ${chromeos___convert_host_id_6b37a758.FaaS.ConvertDeviceId.ChromeOS-ConvertHostID.device_id}
            params:
                query:
                    OrgUnitPath: ${get_ou_from_collection_8377f9b2.FaaS.CollectionActions.get_ou_from_collection.original_ou_id}
    get_ou_from_collection_8377f9b2:
        next:
            - chromeos__move_devices_to_ou_d049cc27
        id: functions.CollectionActions.get_ou_from_collection
        properties:
            host_id: ${host_id}
