name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create TAR archive
        run: |
          PROJECT_NAME="foundry-chromeos-device-actions"
          VERSION=${{ github.event.release.tag_name }}
          TAR_NAME="${PROJECT_NAME}-${VERSION}.tar.gz"
          mkdir out
          cp -r LICENSE manifest.yml collections functions ui workflows api-integrations out
          echo "$(VERSION)" > out/VERSION
          tar -cvzf $TAR_NAME -C out .

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} *.tar.gz
